sensors:
  cameras:
    left_camera:
      device_id: "218622275075"
    front_camera:
      device_id: "215222073684"
    right_camera:
      device_id: "128422272697"

robot:
  _target_: gello.robots.yam.YAMRobot
  channel: can_left
agent:
  _target_: gello.agents.gello_agent.GelloAgent
  port: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FTAO9WPU-if00-port0
  dynamixel_config:
    _target_: gello.agents.gello_agent.DynamixelRobotConfig
    joint_ids: [1, 2, 3, 4, 5, 6]
    joint_offsets: [3.14159, 3.14159, 3.14159, 3.14159, 3.14159, 3.14159]
    joint_signs: [1.0, -1.0, -1.0, -1.0, 1.0, 1.0]
    gripper_config: [7, 55.869140625, 108.369140625]
  start_joints: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
hz: 30
max_steps: 1000

# Data collection configuration
collection:
  max_episode_length: 10000
  act_noise_std: 0.001
  no_ops_threshold: 0.004
  no_ops_last_detected_time: 3
  lock_rotation_detected_time: 1

# Data storage configuration
storage:
  episodes: 30
  base_dir: "/home/sean/Desktop/YAM/gello_software/data_recurrent"
  task_directory: "test"
  language_instruction: "stack cube into pyramid"
  teleop_device: "oculus" # ["oculus", "keyboard", "gello", "none"]
  save_format: "json" # ["json", "npy"]
  old_format: false

# Policy configuration
policy:
  # _target_: lerobot.policies.pi05.configuration_pi05.PI05Config
  type: "dp"
  repo_id: "williamtsai726/stop_the_rolling_glue_0206"
  checkpoint_path: "/home/sean/Desktop/YAM/lerobot/outputs/stop_the_rolling_glue_0206/checkpoints/100000/pretrained_model"